### ISSUE TITLE
Improve Pagination Logic and Error Handling in Scraping Script

### ISSUE THREAD

**Issue by SeleniumRock** [SeleniumRock/Binance-P2P-Scraper#1]
The current pagination logic in the web scraping script may not handle page navigation correctly, especially when dealing with dynamic page elements. This can result in skipped pages or failed navigation. Additionally, the script lacks comprehensive error handling for cases where rows or specific elements may not be present on the page.

_Proposed Changes:_
- Implement improved pagination logic to ensure all available pages are scraped.
- Add explicit error handling for scenarios where elements are not found or where the pagination might not load correctly.
- Ensure that the script continues gracefully without crashing in case of errors.

**Comment by dhir4j** [comment]
def paginate_and_load_pages(driver):
    """Handle pagination and load up to the available pages."""
    all_advertisers = []
    all_prices = []
    all_amounts = []
    all_payment_methods = []

    # Get available pages from the pagination elements
    page_numbers = get_page_numbers(driver)
    max_pages = max(page_numbers) if page_numbers else 1  # Default to 1 if no pages found

    current_page_num = 1

    # Explicitly wait for the first page to fully load
    wait_for_page_to_load(driver)

    # Scrape the first page without navigating
    print(f"Scraping page {current_page_num} (first page)...")
    advertisers, prices, amounts, payment_methods = scrape_page(driver)
    all_advertisers.extend(advertisers)
    all_prices.extend(prices)
    all_amounts.extend(amounts)
    all_payment_methods.extend(payment_methods)

    # Now handle the pagination starting from page 2
    while current_page_num < max_pages:
        # Close any potential overlays
        close_overlays(driver)

        # Find the next page number
        next_page = current_page_num + 1
        if next_page <= max_pages:
            next_page_xpath = f"//div[@class='bn-pagination-item'][text()='{next_page}']"
            print(f"Clicking page number {next_page}...")
            click_element(driver, next_page_xpath)

            # Explicitly wait for the page to load
            wait_for_page_to_load(driver)

            # Update current page number after successfully navigating
            current_page_num = next_page

            # Scrape the new page
            print(f"Scraping page {current_page_num}...")
            advertisers, prices, amounts, payment_methods = scrape_page(driver)
            all_advertisers.extend(advertisers)
            all_prices.extend(prices)
            all_amounts.extend(amounts)
            all_payment_methods.extend(payment_methods)
        else:
            print(f"No more pages or max page limit reached ({max_pages}).")
            break

    return all_advertisers, all_prices, all_amounts, all_payment_methods

def get_page_numbers(driver):
    """Retrieve the available page numbers from the pagination."""
    try:
        page_elements = WebDriverWait(driver, 5).until(
            EC.presence_of_all_elements_located((By.XPATH, "//div[@class='bn-pagination-item']"))
        )
        return [int(elem.text) for elem in page_elements if elem.text.isdigit()]
    except TimeoutException:
        print("Timeout while waiting for pagination elements.")
        return []

**Comment by dhir4j** [comment]
We will first get all the available page numbers using javascirpt selector elements and then click next page button until we hit the last page

**Comment by SeleniumRock** [comment]
@dhir4j Let me check it

**Comment by SeleniumRock** [comment]
@dhir4j Great, this is working perfectly fine.
